### ISSUE TITLE
Provider io.takari.builder.apt.BuilderMojoGenerator not found

### ISSUE THREAD

**Issue by guw** [takari/io.takari.m2e.team#6]
I get the following exception after updating Takari today:

Eclipse IDE for Eclipse Committers

Version: Photon Release Candidate 3 (4.8.0RC3)
Build id: 20180607-0625

Takari Build Lifecycle support	
0.1.0.201806191455
io.takari.m2e.lifecycle.feature.feature.group

java.version=10.0.1
java.version.date=2018-04-17

```
java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider io.takari.builder.apt.BuilderMojoGenerator not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader.access$200(ServiceLoader.java:390)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager$DiscoveredProcessors.hasNext(AnnotationProcessorManager.java:87)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager.discoverNextProcessor(AnnotationProcessorManager.java:118)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager.processAnnotations(AnnotationProcessorManager.java:143)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at io.takari.maven.plugins.compile.jdt.CompilerJdt$FullCompilationStrategy.compile(CompilerJdt.java:434)
	at io.takari.maven.plugins.compile.jdt.CompilerJdt.compile(CompilerJdt.java:554)
	at io.takari.maven.plugins.compile.AbstractCompileMojo.execute(AbstractCompileMojo.java:412)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:140)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:348)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$12.call(MavenImpl.java:1455)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$12.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1453)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:163)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:176)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:119)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:90)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:218)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

```

**Comment by guw** [comment]
The issue does also happen on Java 8. The stack trace is a bit different there:

```
java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider io.takari.builder.apt.BuilderMojoGenerator not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager$DiscoveredProcessors.next(AnnotationProcessorManager.java:92)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager$DiscoveredProcessors.next(AnnotationProcessorManager.java:1)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager.discoverNextProcessor(AnnotationProcessorManager.java:119)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:116)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at io.takari.maven.plugins.compile.jdt.AnnotationProcessorManager.processAnnotations(AnnotationProcessorManager.java:143)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:915)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:437)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at io.takari.maven.plugins.compile.jdt.CompilerJdt$FullCompilationStrategy.compile(CompilerJdt.java:434)
	at io.takari.maven.plugins.compile.jdt.CompilerJdt.compile(CompilerJdt.java:554)
	at io.takari.maven.plugins.compile.AbstractCompileMojo.execute(AbstractCompileMojo.java:412)
...

```
